# working directory
wdir: /homes/jmaathuis/Documents/STATR_pipeline/

# resources
resources: resources/
py_scripts: scripts/Python_scripts/
r_scripts: scripts/R_scripts/
trimmomatic: Trimmomatic-0.39/trimmomatic-0.39.jar

# results
result: result/

# workflow
rules: workflow/rules/

# needed files 
files: resources/example_files/
samples:
    Eco_Ctrl1: Eco_Ctrl1
    Eco_Ctrl2: Eco_Ctrl2
    Eco_Exp1: Eco_Exp1
    Eco_Exp2: Eco_Exp1
adapter: RiboSeq_adapter_as.fa  
genome: NC_000913.3

# extensions
fastq: .fastq.gz
smk: .smk