# working directory, change path
wdir: /path/to/working/directory

# resources
resources: resources/
py_scripts: scripts/Python_scripts/
r_scripts: scripts/R_scripts/
trimmomatic: Trimmomatic-0.39/trimmomatic-0.39.jar

# results
result: result/

# workflow
rules: workflow/rules/

# needed files 
files: resources/example_files/
samples:
    # change name of samples
    Sample1: Sample1 
    Sample2: Sample2 
    # .
    # .
    # .
    # Sample i: sample i
# change name of adapter
adapter: name_of_adapter.fa  
# change name of genome
genome: name_of_genome

# extensions
fastq: .fastq.gz
smk: .smk